Check csrc changes

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,13 +11,20 @@ on:
 jobs:
   build-wasm:
     runs-on: ubuntu-latest
-    # container:
-    #   image: ghcr.io/juniorrojas/algovivo/llvm11-enzyme:latest
     steps:
       - name: Clone repo
         uses: actions/checkout@v4
       - name: Codegen
         run: python utils/codegen/codegen_csrc.py
+      - name: Verify csrc directory is unchanged
+        run: |
+          if [[ $(git status --porcelain csrc) ]]; then
+            echo "Error: csrc has changes after codegen.";
+            git diff csrc;
+            exit 1;
+          else
+            echo "csrc is unchanged.";
+          fi
       - name: Build WASM
         run: |
           docker run \
